version: "3.8"
services:
  db:
    container_name: db
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - ./table.sql:/docker-entrypoint-initdb.d/table.sql
    environment:
      MYSQL_DATABASE: SQLdb
      MYSQL_ROOT_PASSWORD: root
    networks:
      alonkarnw:
        ipv4_address: 192.168.21.14

  api:
    depends_on:
      - db
    build:
      dockerfile: Dockerfile
      context: "./server"
    container_name: api
    ports:
      - 5500:5500
    networks:
      alonkarnw:
        ipv4_address: 192.168.21.12

  nginx:
    build: 
      dockerfile: Dockerfile
      context: "./nginx"
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./client/dist:/usr/share/nginx/html 
      - /nginx/default.conf:/etc/nginx/conf.d/default.conf

      - C:/development/quadacademy/CBP/task-12/scripts/client/dist:/usr/share/nginx/html 
      - C:/development/quadacademy/CBP/task-12/scripts/nginx/default.conf:/etc/nginx/conf.d/default.conf
   
    networks:
      alonkarnw:
        ipv4_address: 192.168.21.10
    stdin_open: true

networks:
  alonkarnw:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.21.0/24
